name: quate_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_spinkit: ^5.2.0
  get_it: ^7.6.4
  hexcolor: ^3.0.1
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  connectivity_plus: ^5.0.2


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/quateIcon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: GemunuLibre
      fonts:
        - asset: assets/fonts/GemunuLibre-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/GemunuLibre-Light.ttf
          weight: 300
        - asset: assets/fonts/GemunuLibre-Regular.ttf
          weight: 400
        - asset: assets/fonts/GemunuLibre-Medium.ttf
          weight: 500
        - asset: assets/fonts/GemunuLibre-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GemunuLibre-Bold.ttf
          weight: 700
        - asset: assets/fonts/GemunuLibre-ExtraBold.ttf
          weight: 800
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
